### PR TITLE
added fix for failing preconfigure_nic & bumped the version to 2.0.3

### PR DESCRIPTION
**Pull request by jrzeszutek**

### CODE REVIEW

**Comment by EarthmanT** [comment]
Hi @jrzeszutek Thanks for the PR. Why does this prevent the issue? It seems the root cause is packaging the pyvcloud from their [broken](https://github.com/vmware/pyvcloud/pull/784) releases in PyPi.

**Comment by jrzeszutek** [comment]
> Hi @jrzeszutek Thanks for the PR. Why does this prevent the issue? It seems the root cause is packaging the pyvcloud from their [broken](https://github.com/vmware/pyvcloud/pull/784) releases in PyPi.

Hi @EarthmanT I think this is not related to the previous issue, this is something else. At the debug session, the file which you mention was replaced already, so the one you fixed was in use at that moment. The deployment was still failing, but not in every execution, with this error: https://github.com/cloudify-cosmo/cloudify-common/blob/3bb3c08c2bdce5514ea55122d8b8ca0b96c16544/cloudify/manager.py#L512  So I suppose it was failing only when there was a retry operation. It tried to set a message in the runtime properties of the target node (server?) using the port relationship, which is not supported I guess (I'm not sure, but the error message says so). After removing this part, it stopped failing.

**Review by EarthmanT — APPROVED** [review]

**Comment by EarthmanT** [comment]
@jrzeszutek OK thanks. Merged. Will you build a new wagon - making sure to get the fork of the pyvcloud?

**Comment by jrzeszutek** [comment]
@EarthmanT This is another issue, but I don't have it fixed. Looks like the wagon builder we have in dockerhub is ignoring the constraints.txt file
[wagon_builder_constraints_issue.txt](https://github.com/cloudify-cosmo/cloudify-vcloud-plugin/files/7720552/wagon_builder_constraints_issue.txt)

**Pull request merged**
